export const TWURPLE_MODULE_CONNECTION = 'default'
export const TWURPLE_MODULE_CONNECTION_API_TOKEN = 'TwurpleModuleConnectionApiToken'
export const TWURPLE_MODULE_CONNECTION_CHAT_TOKEN = 'TwurpleModuleConnectionChatToken'
export const TWURPLE_MODULE_CONNECTION_PUBSUB_TOKEN = 'TwurpleModuleConnectionPubsubToken'
export const TWURPLE_MODULE_OPTIONS_TOKEN = 'TwurpleModuleOptionsToken'
